<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/26 0026
 * Time: 14:26
 */

namespace app\controllers;


use yii\log\FileTarget;
use yii\web\Controller;

class ErrorController extends Controller
{
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		$this->layout = false;
	}

	public function actionError(){
		//记录错误信息到文件和数据库
		$error = \Yii::$app->errorHandler->exception;
		$error_msg = '';
		if( $error ){
			$file = $error->getFile();
			$line = $error->getLine();
			$message = $error->getMessage();
			$code = $error->getCode();

			$log = new FileTarget();
			$log->logFile = \Yii::$app->getRuntimePath() . '/logs/error.log';

			$error_msg = $message . " [file:{$file}][line:{$line}][code:{$code}][url:{$_SERVER['REQUEST_URI']}][POST_DATA". http_build_query( $_POST ) ."]";

			$log->messages[] = [
				$error_msg,
				1,
				'application',
				microtime( true )
			] ;

			$log->export();
			//Todo 写入到数据库

		}
		return $this->render('error',['error'=>$error_msg]);
//		return '~错误页面!<br/>'.'~错误信息:'.$error_msg;
	}
}